title: Ellyana Linden # your name (or website title) here
logo: "/images/pp_edit.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Pharmacist passionate about AI/Machine Learning programming. I would like to integrate AI/Machine Learning with pharmacy to improve medication use, hence, promote patient safety. 
  <br><br>
  <a href="https://www.linkedin.com/in/ellyana-linden/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-135431191-1 # your Google Analytics tracking ID here
